import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero'
import About from '../components/About'


export default function Home() {
  return (
    <div>
      <Head>
        <title>InfinityClub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Hero />     
      <About /> 
    </div>
  )
}
